services:
  prtestdb:
    image: postgres:16-alpine
    container_name: prtestapp-prtestdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prtestdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  prtestapp:
    build: .
    container_name: prtestapp-prtestapp
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@prtestdb:5432/prtestdb
    depends_on:
      prtestdb:
        condition: service_healthy
    command: ["node", "dist/index.js"]
